# -*- coding: utf-8 -*-
"""17_Fakedatadetection_notebook.ipynb.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHkK6UaWi_BRiYyczOCW22QNiFn_WHH8

# **Fake News Detection-TechCrush AI/ML Bootcamp Capstone**

##**Dataset**: WELFake - Word embedding linguistic Features for Fake news Detection.
##**Source**:kaggle-https://www.kaggle.com/dataset/saurabhshahane/fake-news-classification.

# **Table of contents**
1. Data aquisition
2. Data cleaning
3. Exploratory Data Analysis(EDA)
4. Data processing
5. Modelling
6. Evaluation

# **Library imports**
 We begin by importing all the libraries we need throughout this notebook
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import warnings
warnings.filterwarnings('ignore')

# --- NLP ---
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

# --- Machine Learning ---
from sklearn.model_selection import  train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, classification_report, confusion_matrix,
                             ConfusionMatrixDisplay)

# --- Deep Learning ---
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Embedding, LSTM, GlobalMaxPooling1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping

# Download NLTK resources
nltk.download('stopwords')
nltk.download('punkt')

# Set global plot style
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams['figure.figsize'] = (10, 5)

print('All libraries loaded successfully.')

"""
1. Data Acquisition

About the Dataset

The dataset used in this project is the WELFake dataset (Word Embedding over Linguistic Features for Fake News Detection), published by Verma et al. (2021). It was retrieved from Kaggle at:
https://www.kaggle.com/datasets/saurabhshahane/fake-news-classification"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path= '/content/drive/MyDrive/archive (1).zip'

with zipfile.ZipFile(zip_path,'r') as zip_ref:
    zip_ref.extractall('/content/drive/MyDrive/')

print('Extracted successfully')

import os

 for root, dirs, files in os.walk('/content/drive/MyDrive/'):
     for file in files:
        if '.csv' in file.lower():
            print(os.path.join(root,file))

# Load the WELFake dataset.
# If running on Colab, upload the CSV file first using the Files panel,
# or mount Google Drive and adjust the path accordingly.
# Source: https://www.kaggle.com/datasets/saurabhshahane/fake-news-classification
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/WELFake_Dataset.csv')

print('Dataset loaded.')
print(f'Shape: {df.shape}')
df.head()

#A quick overview of datat types and non-null counts foer each column.
df.info()

# Check the distribution of the target label at acquisition stage.
print('Label distribution (raw):')
print(df['label'].value_counts())
print(f'\nFake news (0): {(df["label"]==0).sum()} | Real news (1): {(df["label"]==1).sum()}')

"""##**2.Data Cleaning**
 In this section we  inspect and resolve every data quality issue we find, and we document the reasoning behind every decision.

##**2.1 Drop the Serial Index Column**

The Unnamed: 0 column is just a row number that carries no predictive information. Keeping it is  mislead certain models into treating it as a feature, so we remove it.
"""

# Drop the redundant serial index column.
df.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
print('Remaining columns:', df.columns.tolist())

""" ##** 2.2 Duplicate Rows**

Because the WELFake dataset was assembled by merging four separate corpora, the same article could appear more than once. Duplicate rows would cause data leakage and would inflate any evaluation metric.
"""

# Count and remove duplicates.
n_before = len(df)
df.drop_duplicates(inplace=True)
n_after = len(df)
print(f'Duplicate rows removed: {n_before - n_after}')
print(f'Rows remaining: {n_after}')

"""##** 2.3 Missing Values**

We check both title and text for null values.
"""

# Check missing values per column.
print('Missing values per column:')
print(df.isnull().sum())
print(f'\nTotal rows before handling nulls: {len(df)}')

# Drop rows where 'text' is null — body text is the core feature.
df.dropna(subset=['text'], inplace=True)

# Fill missing titles with empty string rather than dropping the row.
df['title'].fillna('', inplace=True)

print(f'Total rows after handling nulls: {len(df)}')
print('\nMissing values after cleaning:')
print(df.isnull().sum())

"""##**2.4 Data Types**

We confirm all columns hold the expected types. The label column should be an integer; title and text should be strings.
"""

# Inspect data types.
print(df.dtypes)

# Ensure label is integer.
df['label'] = df['label'].astype(int)

# Ensure text columns are strings.
df['title'] = df['title'].astype(str)
df['text']  = df['text'].astype(str)

print('\nData types after correction:')
print(df.dtypes)

"""# ** 2.5 Outliers — Text Length**

For NLP tasks, "outliers" appear as articles that are extremely short (1–2 words) or extremely long. Very short articles may be spam or data errors rather than genuine news. Very long articles do not harm most models but can slow training.

We inspect the word count distribution and remove entries where the full combined text has fewer than 10 words, as these offer insufficient signal.
"""

# Compute word counts for the 'text' column.
import matplotlib.pyplot as plt
df['text_word_count'] = df['text'].apply(lambda x: len(x.split()))

print('Word count statistics for the text column:')
print(df['text_word_count'].describe())

# Visualise the distribution (capped at 2000 words for readability).
plt.figure(figsize=(10, 4))
df['text_word_count'].clip(upper=2000).hist(bins=60, color='steelblue', edgecolor='white')
plt.title('Distribution of Article Word Counts (clipped at 2000)')
plt.xlabel('Word Count')
plt.ylabel('Number of Articles')
plt.tight_layout()
plt.show()

# Remove articles with fewer than 10 words — too short to be real news content.
n_before = len(df)
df = df[df['text_word_count'] >= 10].copy()
print(f'\nRows removed (< 10 words): {n_before - len(df)}')
print(f'Rows remaining: {len(df)}')

# Drop helper column — it was only needed for cleaning.
df.drop(columns=['text_word_count'], inplace=True)

"""##**2.6 Cleaning Summary**

| Issue | Action Taken | Reason |
|-------|-------------|--------|
| Serial index column | Dropped | No predictive value |
| Duplicate rows | Dropped | Prevent data leakage |
| Null `text` values | Dropped rows | Core feature; imputation would be misleading |
| Null `title` values | Filled with `''` | Title is supplementary; preserving the row is better |
| Wrong data types | Corrected | Model expects int labels, string text |
| Very short articles (<10 words) | Dropped | Not genuine news content |

## **3. Exploratory Data Analysis (EDA)**

EDA helps us understand the data before we model it. Every visualisation in this section is followed by a written observation that either influences a preprocessing decision or confirms an assumption about the data.

##**3.1 Class Distribution**

Understanding whether the dataset is balanced is essential. Imbalanced classes would require strategies like class weighting or oversampling.
"""

label_counts = df['label'].value_counts()
label_names  = ['Fake (0)', 'Real (1)']

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Bar chart
axes[0].bar(label_names, label_counts.values, color=['#e74c3c', '#2ecc71'], edgecolor='black')
axes[0].set_title('Class Distribution — Absolute Counts')
axes[0].set_xlabel('Label')
axes[0].set_ylabel('Count')
for i, v in enumerate(label_counts.values):
    axes[0].text(i, v + 200, str(v), ha='center', fontweight='bold')

# Pie chart
axes[1].pie(label_counts.values, labels=label_names, autopct='%1.1f%%',
            colors=['#e74c3c', '#2ecc71'], startangle=90)
axes[1].set_title('Class Distribution — Proportion')

plt.suptitle('Target Label Distribution', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""**Observation**: The dataset is nearly balanced — approximately 51% fake and 49% real news. This is a deliberate property of WELFake (the authors ensured near-equal representation). Because there is no meaningful class imbalance, we do not need to apply oversampling (SMOTE) or adjust class weights in our models. Accuracy remains a valid primary metric, though we will still report precision, recall, and F1 per class.

##**3.2 Article Length Distribution by Class**

We compare the word count distributions between fake and real articles. A consistent difference could mean article length is itself a useful feature.
"""

df['word_count'] = df['text'].apply(lambda x: len(x.split()))

plt.figure(figsize=(11, 5))
for label, color, name in zip([0, 1], ['#e74c3c', '#2ecc71'], ['Fake', 'Real']):
    subset = df[df['label'] == label]['word_count'].clip(upper=1500)
    plt.hist(subset, bins=60, alpha=0.55, color=color, label=name, edgecolor='white')

plt.title('Article Word Count Distribution by Class')
plt.xlabel('Word Count (clipped at 1500)')
plt.ylabel('Frequency')
plt.legend()
plt.tight_layout()
plt.show()

print('Median word count — Fake:', df[df['label']==0]['word_count'].median())
print('Median word count — Real:', df[df['label']==1]['word_count'].median())

"""Observation: Both classes show a right-skewed distribution (most articles are short to medium length). Real articles tend to have a slightly higher median word count than fake ones, suggesting that fake news articles can sometimes be briefer. This difference is not dramatic enough to use word count alone as a feature, but it confirms that the textual content carries meaningful signal that our TF-IDF vectoriser and LSTM model should capture.

## **3.3 Title Length Distribution**

Clickbait headlines are often associated with fake news. A difference in title length between classes could be informative.
"""

df['title_word_count'] = df['title'].apply(lambda x: len(x.split()))

plt.figure(figsize=(11, 5))
for label, color, name in zip([0, 1], ['#e74c3c', '#2ecc71'], ['Fake', 'Real']):
    subset = df[df['label'] == label]['title_word_count'].clip(upper=40)
    plt.hist(subset, bins=40, alpha=0.55, color=color, label=name, edgecolor='white')

plt.title('Title Word Count Distribution by Class')
plt.xlabel('Title Word Count')
plt.ylabel('Frequency')
plt.legend()
plt.tight_layout()
plt.show()

print('Mean title word count — Fake:', round(df[df['label']==0]['title_word_count'].mean(), 2))
print('Mean title word count — Real:', round(df[df['label']==1]['title_word_count'].mean(), 2))

"""Observation: Fake news headlines tend to be slightly shorter on average than real ones. This is consistent with research suggesting that sensationalist, clickbait titles are typically concise and punchy. This finding motivates our decision in the preprocessing stage to combine title and text into a single feature — the title character carries useful signal that would be lost if we only fed text into the model.

### 3.4 Top Words in Fake vs Real News
Looking at the most frequent words (after removing stopwords) in each class reveals whether the vocabulary differs systematically.
"""

from collections import Counter

stop_words = set(stopwords.words('english'))

def get_top_words(texts, n=20):
    """Return the n most common non-stopword tokens."""
    words = []
    for text in texts:
        tokens = re.sub(r'[^a-zA-Z\s]', '', text.lower()).split()
        words.extend([w for w in tokens if w not in stop_words and len(w) > 2])
    return Counter(words).most_common(n)

fake_words = get_top_words(df[df['label']==0]['text'])
real_words = get_top_words(df[df['label']==1]['text'])

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for ax, words, title, color in zip(
    axes,
    [fake_words, real_words],
    ['Top 20 Words — Fake News', 'Top 20 Words — Real News'],
    ['#e74c3c', '#2ecc71']
):
    labels_w, counts = zip(*words)
    ax.barh(labels_w[::-1], counts[::-1], color=color, edgecolor='black')
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel('Frequency')

plt.suptitle('Most Frequent Words by Class (stopwords removed)', fontsize=14)
plt.tight_layout()
plt.show()

"""Observation: Real news articles contain more formal, journalistic vocabulary (e.g., "said", "president", "government", "state"). Fake news articles show more emotionally charged or politically polarising language. The vocabulary sets overlap but are not identical, which confirms that a bag-of-words or TF-IDF representation should be capable of separating the two classes.

##**Unique Word Count (Lexical Diversity)**

A higher ratio of unique words to total words (type-token ratio) might indicate more varied, journalistic writing.
"""

# Compute lexical diversity (unique words / total words) for a random sample of 5000 rows.
# Sampling is done for speed; the trend is stable across the full dataset.
import seaborn as sns

sample = df.sample(5000, random_state=42).copy()  # Assisted by Claude, adapted for this dataset
sample['lex_diversity'] = sample['text'].apply(
    lambda x: len(set(x.lower().split())) / max(len(x.split()), 1)
)

plt.figure(figsize=(10, 5))
for label, color, name in zip([0, 1], ['#e74c3c', '#2ecc71'], ['Fake', 'Real']):
    sns.kdeplot(sample[sample['label']==label]['lex_diversity'],
                fill=True, color=color, alpha=0.45, label=name)
plt.title('Lexical Diversity Distribution by Class')
plt.xlabel('Type-Token Ratio (unique words / total words)')
plt.ylabel('Density')
plt.legend()
plt.tight_layout()
plt.show()

"""Observation: The distributions largely overlap, though real news articles show a slight shift toward higher lexical diversity. This suggests that real news uses a wider vocabulary — consistent with professional journalism. The overlap means lexical diversity alone cannot separate the classes, but it is a signal worth capturing.

Correlation Between Numerical Features and Label

We compute a correlation matrix on the numerical columns we have created (word counts, lexical diversity) to see if any are meaningfully correlated with the label.
"""

# Recreate helper columns needed for correlation
df['word_count'] = df['text'].apply(lambda x: len(x.split()))
df['title_word_count'] = df['title'].apply(lambda x: len(x.split()))
df['lex_diversity'] = df['text'].apply(
    lambda x: len(set(x.lower().split())) / max(len(x.split()), 1)
)

num_df = df[['word_count', 'title_word_count', 'lex_diversity', 'label']].copy()

plt.figure(figsize=(7, 5))
corr = num_df.corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            linewidths=0.5, square=True)
plt.title('Correlation Heatmap — Numerical Features vs Label')
plt.tight_layout()
plt.show()

# Drop after use
df.drop(columns=['word_count', 'title_word_count', 'lex_diversity'],
        inplace=True, errors='ignore')

"""Observation: None of the numerical features alone show a strong linear correlation with the label. This confirms our intuition: the discriminating information lies in the content and vocabulary of the articles, not in simple length metrics. We will therefore rely on text-based features (TF-IDF and word embeddings) as our primary inputs, rather than hand-crafted numeric features.

##**4. Data Preprocessing**

Raw text cannot be fed directly to most machine learning models. In this section we transform the text into numerical representations that our models can process. Every decision is explained.

##**4.1 Combine Title and Text**

Why combine? Both the headline and the body of an article carry signal. Headlines can be misleading clickbait (a strong fake-news indicator), while the body provides richer contextual language. Concatenating them gives the model access to both.

We separate them with a period so that the boundary between headline and body is not treated as a single token.
"""

# Combine title and text into a single column. Assisted by Claude, adapted here.
df['content'] = df['title'] + ' . ' + df['text']
print('Sample combined content:')
print(df['content'].iloc[0][:300])

"""##**4.2 Text Cleaning Function**

Before vectorising, we clean the text by:

Converting to lowercase (so "Trump" and "trump" map to the same token)
Removing URLs (they are noise in this task)
Removing punctuation and special characters
Removing numbers (generally not informative for fake news classification)
Removing stopwords (high-frequency, low-information words like "the", "is")
Applying stemming (reducing words to their root form to reduce vocabulary size)
Why stemming over lemmatisation? Stemming is faster and for a large dataset with TF-IDF, the crude truncation it performs is sufficient. Lemmatisation would be preferred in a production system or with a smaller vocabulary budget.
"""

stop_words = set(stopwords.words('english'))
stemmer    = PorterStemmer()

def clean_text(text):
    """Clean and normalise a news article string."""
    text = text.lower()                                          # lowercase
    text = re.sub(r'https?://\S+|www\.\S+', '', text)           # remove URLs
    text = re.sub(r'[^a-z\s]', '', text)                        # keep only letters
    tokens = text.split()
    tokens = [stemmer.stem(w) for w in tokens if w not in stop_words and len(w) > 2]
    return ' '.join(tokens)

# Apply cleaning. This may take 1–2 minutes on the full dataset.
df['clean_content'] = df['content'].apply(clean_text)

print('Sample cleaned content:')
print(df['clean_content'].iloc[0][:300])

"""
##**4.3 Train / Test Split**

Split ratio: 80% train, 20% test.
With ~66,000 rows remaining, a 20% test set gives approximately 13,000 unseen samples — large enough to produce stable evaluation metrics. We use str"""

X = df['clean_content']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

print(f'Training set size : {len(X_train)}')
print(f'Test set size     : {len(X_test)}')
print(f'Train label distribution:\n{y_train.value_counts()}')

"""##**4.4 TF-IDF Vectorisation (for ML models)**

What is TF-IDF? Term Frequency–Inverse Document Frequency converts text into a numerical matrix where each value reflects how important a word is to a particular document relative to the whole corpus. Words that appear in every article (low IDF) receive lower weights than words that are distinctive to certain articles.

Why TF-IDF over raw Bag-of-Words? Bag-of-Words weights all words equally by count, which means very common words dominate. TF-IDF down-weights those common words, giving more importance to discriminating vocabulary.

Parameters chosen:

max_features=100000: Keep the 100,000 most frequent terms. This balances information capture against memory cost.
ngram_range=(1,2): Include both single words and two-word phrases (bigrams). Bigrams like "fake video" or "breaking news" carry more meaning than either word alone.
sublinear_tf=True: Apply log scaling to term frequencies to reduce the effect of very frequent terms.
Important: We fit the vectoriser on training data only and use .transform() on the test set. Fitting on test data would constitute data leakage.
"""

# TF-IDF Vectorisation. Assisted by Claude, adapted for this task.
tfidf = TfidfVectorizer(max_features=100000, ngram_range=(1, 2), sublinear_tf=True)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print('TF-IDF matrix shape (train):', X_train_tfidf.shape)
print('TF-IDF matrix shape (test) :', X_test_tfidf.shape)

"""### **4.5 Sequence Encoding (for LSTM)**
The LSTM model works with integer-encoded word sequences, not TF-IDF vectors. We use Keras's `Tokenizer` to build a vocabulary and `pad_sequences` to make all sequences the same length.

**`max_words=50000`** — we cap vocabulary at the 50,000 most frequent tokens. Rare words add noise and inflate memory.  
**`max_len=300`** — sequences are padded or truncated to 300 tokens. The median article is well under 300 words; longer ones are truncated at the end where redundant content typically sits.
"""

MAX_WORDS = 50000
MAX_LEN = 300

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN, padding='post', truncating='post')

print('Padded sequence shape (train):', X_train_pad.shape)
print('Padded sequence shape (test) :', X_test_pad.shape)

"""##**5. Modelling**

We train three models:

Logistic Regression with TF-IDF — a fast, interpretable baseline
Random Forest with TF-IDF — a stronger ensemble baseline
LSTM Neural Network with word embeddings — a deep learning approach that captures word order
By comparing these, we can see how much

##**5.1 Model 1 — Logistic Regression (Baseline)**

Why Logistic Regression?
Logistic Regression is a natural first choice for binary text classification. It is fast, interpretable, and often performs surprisingly well with TF-IDF features. It gives us a strong performance floor to beat.
"""

lr_model = LogisticRegression(C=1.0, max_iter=1000, solver='lbfgs', random_state=42)
lr_model.fit(X_train_tfidf, y_train)

y_pred_lr = lr_model.predict(X_test_tfidf)
print('Logistic Regression training complete.')

"""##**5.2 Model 2 — Random Forest**

Why Random Forest?
Random Forest is an ensemble of decision trees that reduces overfitting through bagging. It handles high-dimensional TF-IDF features well and is less sensitive to hyperparameter choices than a single decision tree. Comparing it to Logistic Regression tells us whether non-linear feature interactions exist in this data.

Parameters:

n_estimators=100 — 100 trees provide a good balance between variance reduction and training time.
n_jobs=-1 — use all available CPU cores to speed up training on the large TF-IDF matrix.
max_features='sqrt' — at each split, consider √(n_features) features. This is the standard recommendation for classification tasks and reduces correlation between trees.
"""

rf_model = RandomForestClassifier(n_estimators=100, max_features='sqrt',
                                   n_jobs=-1, random_state=42)
rf_model.fit(X_train_tfidf, y_train)

y_pred_rf = rf_model.predict(X_test_tfidf)
print('Random Forest training complete.')

"""## **5.3 Model 3 — LSTM Neural Network**

### Why LSTM?
TF-IDF treats text as a bag of words and loses all word order information. An LSTM (Long Short-Term Memory network) is a type of recurrent neural network specifically designed to learn patterns in sequences. It can capture things like "this is NOT fake" vs "this IS fake" — a negation that TF-IDF would encode similarly.

### Architecture Decisions

| Component | Choice | Reasoning |
|-----------|--------|-----------|
| Embedding layer | 128-dim, trainable | Learns task-specific representations |
| LSTM layer | 128 units | Balances capacity against overfitting |
| Dropout (0.3) | After LSTM | Reduces overfitting |
| Dense (64, ReLU) | Hidden layer | Non-linear transformation before output |
| Dropout (0.3) | After dense | Additional regularisation |
| Output Dense (1, Sigmoid) | 1 neuron | Binary classification: outputs probability of being Real |
| Loss | Binary crossentropy | Appropriate for binary classification |
| Optimizer | Adam | Adaptive learning rate; robust default choice |

### Why Sigmoid at the output?
Sigmoid maps the final score to a probability between 0 and 1. This is correct for binary classification. If this were a multi-class problem, we would use Softmax.

"""

# Build LSTM model. Architecture assisted by Claude, adapted for this task.
lstm_model = Sequential([
    Embedding(input_dim=MAX_WORDS, output_dim=128, input_length=MAX_LEN),
    LSTM(128, return_sequences=False),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
lstm_model.summary()

# Early stopping halts training if validation loss does not improve for 2 consecutive epochs,
# restoring the weights from the best epoch. This prevents overfitting.
early_stop = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

history = lstm_model.fit(
    X_train_pad, y_train,
    epochs=10,
    batch_size=256,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

# Plot training and validation accuracy / loss curves.
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['accuracy'],     label='Train Accuracy', marker='o')
axes[0].plot(history.history['val_accuracy'], label='Val Accuracy',   marker='o')
axes[0].set_title('LSTM — Accuracy over Epochs')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()

axes[1].plot(history.history['loss'],     label='Train Loss', marker='o', color='#e74c3c')
axes[1].plot(history.history['val_loss'], label='Val Loss',   marker='o', color='#c0392b')
axes[1].set_title('LSTM — Loss over Epochs')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()

plt.suptitle('LSTM Training Curves', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Generate binary predictions from the LSTM (threshold = 0.5).
y_pred_lstm_prob = lstm_model.predict(X_test_pad, batch_size=256).flatten()
y_pred_lstm = (y_pred_lstm_prob >= 0.5).astype(int)
print('LSTM predictions generated.')

"""6. Evaluation

We evaluate all three models using the full set of classification metrics required: Accuracy, Precision, Recall, F1 Score (per class), and a Confusion Matrix. We then compare performance and reflect on the results.

6.1 Evaluation Helper Function

We define a reusable function to avoid repeating the same evaluation code for each model.
"""

def evaluate_model(model_name, y_true, y_pred):
    """Print classification metrics and display a confusion matrix."""
    print(f'\n{'='*55}')
    print(f'  {model_name}')
    print(f'{'='*55}')
    print(f'Accuracy : {accuracy_score(y_true, y_pred):.4f}')
    print(f'\nClassification Report (per class):')
    print(classification_report(y_true, y_pred, target_names=['Fake (0)', 'Real (1)']))

    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(6, 5))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])
    disp.plot(ax=ax, colorbar=False, cmap='Blues')
    ax.set_title(f'Confusion Matrix — {model_name}', fontweight='bold')
    plt.tight_layout()
    plt.show()
    return accuracy_score(y_true, y_pred)

acc_lr   = evaluate_model('Logistic Regression', y_test, y_pred_lr)
acc_rf   = evaluate_model('Random Forest',       y_test, y_pred_rf)
acc_lstm = evaluate_model('LSTM Neural Network', y_test, y_pred_lstm)

"""
6.2 Model Comparison Summary"""

# Build comparison table.
results = {
    'Model': ['Logistic Regression', 'Random Forest', 'LSTM Neural Network'],
    'Accuracy': [acc_lr, acc_rf, acc_lstm],
    'Precision (macro)': [
        precision_score(y_test, y_pred_lr,   average='macro'),
        precision_score(y_test, y_pred_rf,   average='macro'),
        precision_score(y_test, y_pred_lstm, average='macro')
    ],
    'Recall (macro)': [
        recall_score(y_test, y_pred_lr,   average='macro'),
        recall_score(y_test, y_pred_rf,   average='macro'),
        recall_score(y_test, y_pred_lstm, average='macro')
    ],
    'F1 Score (macro)': [
        f1_score(y_test, y_pred_lr,   average='macro'),
        f1_score(y_test, y_pred_rf,   average='macro'),
        f1_score(y_test, y_pred_lstm, average='macro')
    ]
}

results_df = pd.DataFrame(results).set_index('Model').round(4)
print(results_df.to_string())

# Visual comparison bar chart.
ax = results_df[['Accuracy', 'F1 Score (macro)']].plot(
    kind='bar', figsize=(10, 5), color=['#3498db', '#e67e22'],
    edgecolor='black', rot=15
)
ax.set_title('Model Comparison — Accuracy and Macro F1 Score', fontweight='bold', fontsize=13)
ax.set_ylabel('Score')
ax.set_ylim(0.85, 1.0)
ax.legend(loc='lower right')
for p in ax.patches:
    ax.annotate(f'{p.get_height():.3f}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=9)
plt.tight_layout()
plt.show()

"""6.3 Interpretation of Results

Key findings:

Logistic Regression establishes a strong baseline. Given the large TF-IDF feature space with bigrams, it captures most of the discriminating vocabulary effectively. High performance here confirms that the lexical content of articles is the primary driver of classification.

Random Forest performs similarly to or slightly below Logistic Regression on this task. This is a known phenomenon with high-dimensional, sparse text features: tree-based methods can struggle because at each split they only consider a subset of the very large feature space, making it hard to find informative splits. Logistic Regression handles the full sparse feature vector more naturally.

LSTM captures sequential relationships between words that TF-IDF cannot represent. If the LSTM outperforms the ML models, it confirms that word order and context (e.g., negations, writing style) carry additional signal beyond vocabulary. If it performs comparably, it suggests that for this dataset the vocabulary alone is the dominant signal.

Weaknesses acknowledged: Our LSTM was trained with a randomly initialised embedding layer. Using pre-trained word embeddings (e.g. GloVe or fastText) would likely improve performance further, as those embeddings encode semantic relationships learned from billions of words. Given the scope of this capstone, we opted for trainable embeddings to remain self-contained.

What we would try next: (a) Pre-trained embeddings, (b) a fine-tuned BERT model for state-of-the-art performance, (c) feature engineering using source domain or publication date if available.

## References

Verma, P. K., Agrawal, P., Amorim, I., & Prodan, R. (2021). WELFake: Word Embedding Over
Linguistic Features for Fake News Detection. *IEEE Transactions on Computational Social Systems*.
https://doi.org/10.1109/TCSS.2021.3068519

Shahane, S. (2021). Fake News Classification [Dataset]. Kaggle.
https://www.kaggle.com/datasets/saurabhshahane/fake-news-classification

Pedregosa, F. et al. (2011). Scikit-learn: Machine Learning in Python.
*Journal of Machine Learning Research*, 12, 2825–2830.
https://scikit-learn.org

claude Ai
"""

import pickle
from google.colab import files

# Save model and vectoriser
pickle.dump(lr_model, open('model.pkl', 'wb'))
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))
print('Saved successfully.')

# Download immediately
files.download('model.pkl')
files.download('tfidf.pkl')